---
apiVersion: v1
kind: Endpoints
metadata:
  name: git-example-svc
  namespace: ingress-nginx
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/ignore-resource-updates: 'true'
subsets:
  - addresses:
      - ip: 198.51.100.19
    ports:
      - port: 443