apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: staging-application-kustomize
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  env: "staging"
          - git:
              repoURL: https://github.com/nh4ttruong/argocd-gitops-spokes.git
              revision: HEAD
              files:
                - path: workloads/*/envs/staging/app.yaml
  template:
    metadata:
      name: "{{index .path.segments 3}}-{{index .path.segments 1}}" # {env}-{appname}
      labels:
        env: staging
        engine: kustomize
        type: application
    spec:
      project: "{{index .path.segments 3}}-apps"
      source:
        repoURL: https://github.com/nh4ttruong/argocd-gitops-spokes.git
        targetRevision: HEAD
        path: "{{.path.path}}"
        kustomize:
          ignoreMissingComponents: true
      destination:
        server: "{{.server}}"
        namespace: "{{.namespace}}" # From app.yaml
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideDiff=true
        retry:
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
          limit: 7
