apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

# For common resources like RBAC, namespaces, etc. that are shared across all environments
resources:
  - namespace.yaml
